name: Action Eslint
on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - uses: reviewdog/action-eslint@v1.18.2
        with:
          eslint_flags: 'src/'
