name: Messager
on: [push, pull_request]

jobs:
  message:
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Echo some data
        run: |
          echo ${{ github.ref }}
          echo ${{ github.base_ref }}
          echo ${{ github.head_ref }}
          echo ${{ github }}
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: |
          if [ -z ${{ github.head_ref }} ]
          then
            echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          else
            echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          fi
      - name: Create message
        run: |
          mkdir -p messages
          echo Running on branch: ${{ steps.extract_branch.outputs.branch }}
          echo Head commit message "${{ env.commitmsg }}" > messages/${{ steps.extract_branch.outputs.branch }}.txt
      - name: Upload message
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ steps.extract_branch.outputs.branch }}
          path: messages/${{ steps.extract_branch.outputs.branch }}.txt
      - name: Download message
        uses: actions/download-artifact@v4
        with:
          name: coverage-${{ steps.extract_branch.outputs.branch }}
      - run: cat messages/${{ steps.extract_branch.outputs.branch }}.txt
      - name: List directory
        run: ls -R
