name: Messager
on: push

jobs:
  message:
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: |
          if [ -z ${{ github.head_ref }} ]
          then
            echo ${GITHUB_REF#refs/heads/}
          else
            echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          fi
      - name: Create message
        run: |
          mkdir -p messages
          echo Running on branch: ${{ steps.extract_branch.outputs.branch }}
          echo Head commit message ${{ env.commitmsg }} > ${{ steps.extract_branch.outputs.branch }}.txt
