name: Messager
on: push

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create message
        run: |
          mkdir -p messages
          echo Coverage 10 on branch ${GITHUB_REF} > messages/${GITHUB_REF##*/}.txt
          echo Running on branch: ${GITHUB_REF##*/}
      - name: Upload message
        uses: actions/upload-artifact@v4
        with:
          name: my-message
          path: messages/messages/${GITHUB_REF##*/}.txt
