name: Messager
on: push

jobs:
  message:
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: |
          if [ -z ${{ github.head_ref }} ]
          then
            echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          else
            echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          fi
      - name: Create message
        run: |
          mkdir -p messages
          echo Running on branch: ${{ steps.extract_branch.outputs.branch }}
          echo Head commit message ${{ env.commitmsg }} > ${{ steps.extract_branch.outputs.branch }}.txt
      - name: Upload message
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ steps.extract_branch.outputs.branch }}
          path: ${{ steps.extract_branch.outputs.branch }}.txt
